
spring:
  application:
    name: springboot #业务名称
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
  boot:
    admin:
      client:
        url: http://127.0.0.1:7070
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

management:
  endpoint:
    health:
      show-details: always
    #启用
    prometheus:
      enabled: true
  #添加应用名称
  #访问metrics数据的路径:/actuator/prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  trace:
    http:
     enabled: true
info:
 auth:
  name: lct
  dep: dev
#其他配置信息
myapp:
  fluentd:
    host: 127.0.0.1
#线上只针对指定的用户启用debug级别的日志输出，搭配配置中心
log.diagnose.enabled: true
log.diagnose.users: zhangsan,lisi
chaos:
  monkey:
    enabled: true
    #注入延迟
    assaults:
      latency-active: true
      latency-range-end: 3000
      latency-range-start: 1000
    watcher:
      controller: true
