server:
  port: 8886
spring:
  application:
    name: cloud-eureka-server
eureka:
  instance:
    hostname: localhost
  server:
    response-cache-update-interval-ms: 10 #只读缓存的更新时间,默认30s
    use-read-only-response-cache: false #是否将只读缓存关闭
  client:
    #register-with-eureka: false #非集群部署时，不需要将自己进行注册
    #fetch-registry: false #非集群部署时，不需从Eureka Server中获取注册表信息
    service-url:
      defaultZone: http://localhost:8882/eureka #集群部署时，配置其他Eureka Server地址
    register-with-eureka: true #集群部署时，需要将自己进行注册
    fetch-registry: true #集群部署时，需要从其他Eureka Server中获取注册表信息

